### ISSUE TITLE
Example for Oculus Quest Standalone

### ISSUE THREAD

**Issue by almavivaxrdeveloper** [Esri/arcgis-maps-sdk-unity-samples#113]
HI,
Is there an example to use the SDK in standalone mode for Oculus Quest?
I'm trying to convert the example but I'm having some problems.
Thank you
   Luca

**Comment by mmgaw113** [comment]
Both the VR sample and XR Table Top Sample will work on the Meta Quest 2 and above for standalone Android builds. The XR Table top uses the Meta XR Plugin for OpenXR to support hand tracking and other Meta Specific features. Please let me know if you have other issues.
