### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by yuhe0925** [Esri/arcgis-maps-sdk-unity-samples#122]
ArcGISViewStateLoggingComponent
ArcGISCameraControllerComponent

are missing from the package, and the name space "using Esri.ArcGISMapsSDK.Samples.Components" is not exsit

**Comment by mmgaw113** [comment]
Navigate to the package manager, then click on the ArcGISMapsSDK for Unity, click on Samples, and then click install samples. This will import the samples and fix the issues you are having.
