### ISSUE TITLE
'ArcGISPoint' does not contain a definition for 'SetZ

### ISSUE THREAD

**Issue by ibytergj** [Esri/arcgis-maps-sdk-unity-samples#42]
Error - Assets\SampleViewer\Samples\FeatureLayer\StadiumInfo.cs(101,26): error CS1061: 'ArcGISPoint' does not contain a definition for 'SetZ' and no accessible extension method 'SetZ' accepting a first argument of type 'ArcGISPoint' could be found (are you missing a using directive or an assembly reference?)

**Comment by mrnelson6** [comment]
This is resolved
