### ISSUE TITLE
Is it possible to just display a 2D map ? 

### ISSUE THREAD

**Issue by genaray** [Esri/arcgis-maps-sdk-unity-samples#54]
Im developing a map based game, however all i need is basically a nice arcgis based flat 2D map... Is this possible ?

**Comment by Dosenbiiir** [comment]
Hi. Yes thats possible. Inside the Map Creator UI (ArcGISMapsSDK) go to the `Elevation` Tab and uncheck the elevation checkbox. The map will be flat now.
Also check if there are active layers for e.g. buildings (3DObject Scene Layer). You find them in the `Layers` Tab.

Cheers.

**Comment by mrnelson6** [comment]
Yea in addition to @Dosenbiiir 's point you can update the camera controller to always look down and also in the map tab select local mode if you don't want to deal with the globe
