### ISSUE TITLE
Unable to install the plugin. 

### ISSUE THREAD

**Issue by paul-bonnel-fr** [Esri/arcgis-maps-sdk-unity-samples#62]
Hello,

I'm unable to try the Unity SDK. I've followed the gettings started tutorial (https://developers.arcgis.com/unity/get-started/)  

Here is a screenshot of the error I have. Can you please advice ? 

I'm using Unity 2021.3.9f1 URP (Macbook Pro M1) and I tried both Android and iOS target. 

Thanks! 

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/33127779/213244203-54a1437f-3cfe-4021-b6af-47fd3480d841.png">

**Comment by tTakeda09** [comment]
Hi,

I'm wondering if you are using Unity 2021.3.x LTS Intel version.
https://developers.arcgis.com/unity/reference/system-requirements/

When you have issues like this, I recommend posting in ArcGIS Maps SDK for Unity community. The Esri community is a user forum where users can help each other and also get help from Esri members. Posting your question in the forum will also help other users when they face the same issues.
https://community.esri.com/t5/arcgis-maps-sdk-for-unity-questions/bd-p/arcgis-maps-sdk-unity-questions

**Comment by paul-bonnel-fr** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/33127779/213427745-fa1fac0a-6890-4cd6-bcea-14d633be91ef.png">
I'm using the Silicon LTS version of Unity. Okay I'm going to check on the Unity Forum... Thanks
