### ISSUE TITLE
Third Person Character Sample for Unity

### ISSUE THREAD

**Issue by franchyze923** [Esri/arcgis-maps-sdk-unity-samples#76]
Wondering if a sample similar to the "Explore with Third Person Character" in the [Unreal SDK ](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/tree/main/sample_project/Content/SampleViewer/Samples/ThirdPersonCharacter) could be added for Unity?

I've been playing around with the Unity built in Third person template - it would be really cool to somehow import an Integrated Mesh Layer (.slpk) and have the character walk around in it.

**Comment by ZackAllen** [comment]
Hi Francis. We have a [third person sample](https://github.com/Esri/arcgis-maps-sdk-unity-samples/tree/main/samples_project/Assets/SampleViewer/Samples/ThirdPerson) for Unity. When using your own .slpk, remember to enable mesh colliders in the ArcGIS Map component.

Zack

**Comment by franchyze923** [comment]
Great! Not sure how I missed that.

**Comment by franchyze923** [comment]
I've added an integrated mesh layer to the project, and I'm able to zoom to the layer. I'd like the level to start at this location and have the player drop onto it. I tried updating both the Origin Position within the ArcGIS Map as well as ArcGIS Location within the Camera (this always seems to snap back to the original position). Any ideas?
