### ISSUE TITLE
Stream layer sample: ClientWebSocket.ReceiveAsync may need to loop over multiple chunks

### ISSUE THREAD

**Issue by markdeaton** [Esri/arcgis-maps-sdk-unity-samples#77]
https://github.com/Esri/arcgis-maps-sdk-unity-samples/blob/d3cedb81c55d939299b4a452300ee1691e3335bc/samples_project/Assets/SampleViewer/Samples/StreamLayer/StreamLayerWebSocketSubscribe.cs#L148

Should probably be implemented as a loop in order to make sure all the payload for a message is gathered.
More info here: https://stackoverflow.com/questions/23773407/a-websockets-receiveasync-method-does-not-await-the-entire-message

**Comment by Jade-JadeH** [comment]
@markdeaton Thanks for raising this issue. The fix got merged.

**Comment by Jade-JadeH** [comment]
forgot to attach the PR but here was it https://github.com/Esri/arcgis-maps-sdk-unity-samples/pull/90 @markdeaton

**Comment by avr757** [comment]
Closing out this issue as it has been fixed!
