### ISSUE TITLE
Missing Sample Files?

### ISSUE THREAD

**Issue by mdefratti** [Esri/arcgis-maps-sdk-unity-samples#98]
I'm trying to add Feature Layer data to my Unity project, using the REST API query method. I'm trying to understand where to add this query within the SDK window, but I can't find the example files mentioned in the readme.
Specifically, this page: https://github.com/Esri/arcgis-maps-sdk-unity-samples/tree/main/samples_project/Assets/SampleViewer/Samples/FeatureLayer 

I searched the repo and can't find "FeatureLayerQuery.cs" ??

**Comment by mmgaw113** [comment]
Sorry for a delay in response. This readme file is actually outdated and the scripts listed no longer exist. There should be an updated readme later today. You can access it [here ](https://github.com/Esri/arcgis-maps-sdk-unity-samples/blob/832f01429aa176321464881d5c095fb1b4bab33d/samples_project/Assets/SampleViewer/Samples/FeatureLayer/readme.md)in the mean time.

We will close this issue once the updated Readme has been merged into main.
